/**
 * Plain CSS custom properties - the neutral output any web consumer (imt-fe
 * included, eventually) can point its own Tailwind/bridge config at. Emits
 * "--<slug>" names only; a consumer's own bridge file (e.g. imt-fe's
 * tokenMap.js) still owns the app-specific class names and fallbacks - that
 * stays out of this package on purpose, same reasoning as core.js's header.
 */
function renderCss(resolved) {
  const light = resolved.map((t) => `  --${t.slug}: ${t.light};`);
  const dark = resolved.filter((t) => t.dark).map((t) => `  --${t.slug}: ${t.dark};`);

  return [
    "/* AUTO-GENERATED by @bluesilo/design-tokens - do not edit by hand. */",
    "",
    ":root {",
    ...light,
    "}",
    "",
    ':root[data-theme="dark"] {',
    ...dark,
    "}",
    "",
  ].join("\n");
}

module.exports = { renderCss };
